-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "login" TEXT,
    "node_id" TEXT,
    "avatar_url" TEXT NOT NULL,
    "gravatar_id" TEXT,
    "url" TEXT,
    "html_url" TEXT,
    "followers_url" TEXT,
    "gists_url" TEXT,
    "starred_url" TEXT,
    "subscriptions_url" TEXT,
    "organizations_url" TEXT,
    "repos_url" TEXT,
    "events_url" TEXT,
    "received_events_url" TEXT,
    "type" TEXT,
    "site_admin" BOOLEAN,
    "name" TEXT,
    "company" TEXT,
    "blog" TEXT,
    "location" TEXT,
    "email" TEXT,
    "hireable" BOOLEAN,
    "bio" TEXT,
    "twitter_username" TEXT,
    "public_repos" INTEGER,
    "public_gists" INTEGER,
    "followers" INTEGER,
    "following" INTEGER,
    "created_at" TIMESTAMP(3),
    "update" TIMESTAMP(3),

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
